volumes:
  output:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/westerd/_/project_data/the_auditor

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  the_auditor:
    build:
      context: ../..
      dockerfile: .devcontainer/the_auditor/Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DEBIAN_FRONTEND=noninteractive
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ../..:/workspace:cached
      - output:/output:rw
    command: ["sh", "-c", "cd /workspace/src && uvicorn the_auditor.main:app --host 0.0.0.0 --port 8000"]
      # ["uvicorn", "the_auditor.main:app", "--host", "0.0.0.0", "--port", "8000"]
      # ["sleep", "infinity"]
      
