volumes:
  output:
    driver: local
    driver_opts:
      type: none
      o: bind,rw
      device: /home/westerd/_/project_data/ward_nre_pipeline/output

  test_data:
    driver: local
    driver_opts:
      type: none
      o: bind,ro
      device: /home/westerd/_/project_data/ward_nre_pipeline/test_data

  input_data:
    driver: local
    driver_opts:
      type: none
      o: bind,ro
      device: /mnt/z/_/data/corpora/ocred_docs_from_pubmed

  quickumls_data:
    driver: local
    driver_opts:
      type: none
      o: bind,ro
      device: /home/westerd/_/project_data/ward_nre_pipeline/quickumls

services:
  nre_pipeline:
    container_name: nre_pipeline-devcontainer
    image: nlpssc/nre_pipeline-devcontainer:latest
    build:
      context: ../..
      dockerfile: .devcontainer/nre_pipeline/Dockerfile
      args:
        umls_key_file: "/home/westerd/_/project_data/ward_nre_pipeline/UMLS_API_KEY.secret"
    volumes:
      - ../..:/workspace:cached
      - output:/output:rw
      - test_data:/test_data:ro
      - input_data:/input_data:ro
      - quickumls_data:/quickumls_data:ro
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - ENVIRONMENT=development
    command: ["sleep", "infinity"]