
version: "3.8"

volumes:
  output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/westerd/_/project_data/ward_nre_pipeline/output
  test_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/westerd/_/project_data/ward_nre_pipeline/test_data
  input_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/z/_/data/corpora/ocred_docs_from_pubmed
services:
  nre_pipeline:
    container_name: nre_pipeline-devcontainer
    image: nlpssc/nre_pipeline-devcontainer:latest
    build:
      context: ../..
      dockerfile: .devcontainer/nre_pipeline/Dockerfile
    volumes:
      - ../..:/workspace:cached
      - output:/output
      - test_data:/test_data
      - input_data:/input_data
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - ENVIRONMENT=development
    command: ["sleep", "infinity"]
