services:
  nre_pipeline:
    container_name: nre_pipeline-devcontainer
    image: nlpssc/nre_pipeline-devcontainer:latest
    build:
      context: ../..
      dockerfile: .devcontainer/nre_pipeline/Dockerfile
    volumes:
      - ../..:/workspace:cached
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - ENVIRONMENT=development
    command: ["sleep", "infinity"]
