volumes:
  hf_cache:
    driver: local
    driver_opts:
      type: none
      device: /data/home/westerd@ds.vumc.io/_/mounts/hf_cache
      o: bind
  logs:
    driver: local
    driver_opts:
      type: none
      device: /data/home/westerd@ds.vumc.io/_/mounts/logs
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: /data/home/westerd@ds.vumc.io/_/mounts/config
      o: bind
  test_data:
    driver: local
    driver_opts:
      type: none
      device: /data/home/westerd@ds.vumc.io/_/mounts/test_data
      o: bind
  input:
    driver: local
    driver_opts:
      type: none
      device: /data/home/westerd@ds.vumc.io/_/mounts/input
      o: bind
  output:
    driver: local
    driver_opts:
      type: none
      device: /data/home/westerd@ds.vumc.io/_/mounts/output
      o: bind
  workspace:
    driver: local
    driver_opts:
      type: none
      device: ..
      o: bind

services:
  devcontainer:
    container_name: mhav_message_classification_devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        BUILDKIT_MAX_PARALLELISM: ${BUILDKIT_MAX_PARALLELISM:-4}
        BUILDKIT_INLINE_CACHE: 1
    image: nlpssc/mhav_message_classification_devcontainer:latest
    volumes:
      - hf_cache:/hf_cache
      - logs:/logs
      - config:/config
      - test_data:/test_data
      - workspace:/workspace
      - input:/input_data
      - output:/output_data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    tty: true
    restart: unless-stopped
    ports:
      - 8000:8000 # instrumentation
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
