import os


NUMBER_DOCS_TO_WRITE_BEFORE_YIELD = 100
NUMBER_DOCS_TO_WRITE_BEFORE_YIELD = os.getenv("NUMBER_DOCS_TO_WRITE_BEFORE_YIELD", None)
if NUMBER_DOCS_TO_WRITE_BEFORE_YIELD is None:
    raise RuntimeError(
        "NUMBER_DOCS_TO_WRITE_BEFORE_YIELD environment variable is not set"
    )
else:
    NUMBER_DOCS_TO_WRITE_BEFORE_YIELD = int(NUMBER_DOCS_TO_WRITE_BEFORE_YIELD)


__all__ = ["NUMBER_DOCS_TO_WRITE_BEFORE_YIELD"]
